version: "3.8"

services:
  flask:
    build: ./flask_app
    volumes:
      - ./data:/data
    environment:
      - FLASK_ENV=development
      - UPLOAD_KEY

  caddy:
    image: caddy:2.7-alpine
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
    ports:
      #- 80:80
      #- 443:443
      - 3006:80
    depends_on:
      - flask
