services:
  flask:
    build: ./flask_app
    volumes:
      - ./data:/data
    environment:
      - FLASK_ENV=development
      - UPLOAD_KEY
      - UPLOAD_URL

  caddy:
    build: ./caddy
    volumes:
      - ./caddy/Caddyfile:/etc/caddy/Caddyfile
      - ./data:/data
    environment:
      - LINODE_PERSONAL_ACCESS_TOKEN
    ports:
      - 80:80
      - 443:443
      # - 3006:80
    depends_on:
      - flask
